return {
    -- "nvim-telescope/telescope.nvim",
    -- dependencies = {
    --     {
    --         "nvim-telescope/telescope-fzf-native.nvim",
    --         build = "make",
    --         config = function()
    --             require("telescope").load_extension("fzf")
    --         end,
    --     },
    --
    -- },
    -- lazy = false,
    -- event = "VimEnter",
    -- config = function()
    --     local telescope = require("telescope")
    --     telescope.setup({
    --         defaults = {
    --             file_ignore_patterns = { "node_modules", "target" },
    --         },
    --     })
    -- end,
}
